cc_test(
    name = "AllowedValues_test",
    size = "small",
    srcs = ["test_AllowedValues.cc",],
    deps = [
            "//src:sudoku-solver",
            "@com_google_googletest//:gtest_main"
            ],
)
