cc_library(
    name = "sudoku-solver",
    srcs = [
            "AllowedValues.cc",
            "Square.cc",
            "Group.cc",
            "Board.cc",
            ],
    hdrs = [
            "AllowedValues.h",
            "Square.h",
            "Group.h",
            "Board.h",
            ],
    deps = [
            "@com_github_google_glog//:glog",
            ],
    visibility = ["//visibility:public"]
#            "//src/test:__pkg__",
#            "//src/app:__pkg__",
#           ]
)

