name: Build/Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    # build project
    - name: mkdir
      run: mkdir build
    - name: cmake build
      run: cmake -S . -B build
    - name: cmake make
      run: cmake --build build
    # run tests
    - name: run test
      run: cd build && ctest .
